### ISSUE TITLE
CORS errors

### ISSUE THREAD

**Issue by cherryontopknife** [AhatLi/SonicClassifier#2]
After editing the config file to match my server settings, I get this console error:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:9255/getPlaylist. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200`

**Comment by AhatLi** [comment]
Hello, Sorry for the inconvenience.
In new SonicClassifier_v0.9.2, cors_disable cofig has been added.
thank you
